In [1]:
import numpy as np
import igl
import meshplot as mp
from scipy.spatial.transform import Rotation
import ipywidgets as iw

In [2]:
with np.load('data/octa_sphere_5.npz') as npl:
    v_s, f_s = npl['v'], npl['f']

In [3]:
v, f = igl.read_triangle_mesh('data/woody-hi.off')
segments_recording = np.zeros(len(v), dtype=int)
print(v.shape)
print(f.shape)
print(v[:5])  # First 5 vertices
print(f[:5])  # First 5 faces (indices of vertices)


(2642, 3)
(5040, 3)
[[  1.  246.5   0. ]
 [  2.5 252.5   0. ]
 [  5.  258.    0. ]
 [  8.  263.    0. ]
 [ 12.  267.    0. ]]
[[ 412  534  532]
 [ 827  397  539]
 [ 319  326  322]
 [ 531  533  191]
 [ 311  306 2208]]


In [4]:
v -= v.min(axis=0)
v /= v.max()

In [5]:
tb = iw.ToggleButtons(description='Segment', options=[1,'+'])
@mp.interact(x=tb)
def s_but(x):
    if x == '+':
        tb.options = list(range(1,len(tb.options)+1)) + ['+']
        tb.value = len(tb.options) - 1
    else:
        tb.current = x

button = iw.Button(description="Paint!")
clear_button = iw.Button(description="Clear!")

# Set Callback
def paint_clicked(b):
    slicer = np.where(np.linalg.norm(v - sf.coord[1:],axis=1) < sf.coord[0])[0]
    segments_recording[slicer] = tb.current
    paint_ui.update_object(oid=0, colors=segments_recording)
def clear_clicked(b):
    segments_recording[segments_recording == tb.current] = 0
    paint_ui.update_object(oid=0, colors=segments_recording)
button.on_click(paint_clicked)
clear_button.on_click(clear_clicked)

# Display Buttons
display(iw.HBox([button, clear_button]))

# Meshplot
paint_ui = mp.plot(v,f,c=segments_recording)
paint_ui.add_mesh(v_s*0.1, f_s, flat=False, c=np.array([1,0,0]))
def sf(radius,x,y,z):
    paint_ui.update_object(oid = 1, vertices = v_s*radius + np.array([x,y,z]))
    sf.coord = [radius,x,y,z]
mp.interact(sf, 
            radius = iw.FloatSlider(min=0.1, max=1, value=0.1),
            x = iw.FloatSlider(min=-0.1, max=1, value=0),
            y = iw.FloatSlider(min=-0.1, max=1, value=0),
            z = iw.FloatSlider(min=-0.1, max=1, value=0))

interactive(children=(ToggleButtons(description='Segment', options=(1, '+'), value=1), Output()), _dom_classes…

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.4306930…

TypeError: Viewer.add_mesh() got an unexpected keyword argument 'flat'

In [ ]:
np.save('data/woody-hi.label.npy', segments_recording)